version: "3.1"

services:
  app:
    container_name: docflow_jar
    image: docflow
    restart: always
    build:
      context: .
#      dockerfile: Dockerfile
    depends_on:
      - postgressqldb
    ports:
      - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgressqldb:5432/docflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATASOURCE_DB: docflow
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - dskbinikorback
    volumes:
      - uploads:/var/lib/uploads
  eureka:
    container_name: eureke_service
    image: docflow
    restart: always
    build:
      context: .
#      dockerfile: Dockerfile
    depends_on:
      - apigateway
    ports:
      - 8761:8761
    networks:
      - dskbinikorback
  apigateway:
    container_name: api_gateway
    image: docflow
    restart: always
    build:
      context: .
#      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - 8083:8083
    networks:
      - dskbinikorback
  postgressqldb:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - dskbinikorback
    volumes:
      - postgres_db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    networks:
      - dskbinikorback
    ports:
      - 8085:8080

volumes:
  postgres_db:
  uploads:
    external: true

networks:
  dskbinikorback:
    driver: bridge
