server:
  port: 8088
spring:
  application.name: backendweb
  datasource:
    url: jdbc:postgresql://localhost:5432/dsk
    username: postgres
    password: 123
  jpa:
    show-sql: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    loadbalancer:
      ribbon:
        enable: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#eureka: default portligi uchun
#  client.service-url.defaultZone: http://localhost:8761/eureka
file:
  upload-dir: ./uploads
