
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/dsk
    username: postgres
    password: 123
    jpa:
      show-sql: false
      hibernate.ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      properties.hibernate.temp.use_jdbc_metadata_defaults: false
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    enable-csrf: true

#  security:
#    enable-csrf: false
  cloud:
    gateway:
      routes:
        - id: backweb
          uri: http://localhost:8088
          predicates:
            - Path=/api/**
        - id: docflow
          uri: http://localhost:8087
          predicates:
            - Path=/doc/**
#        - id: secondserver
#          uri: lb://secondserver
#          predicates:
#            - Path=/pai/**
#        - id: backendweb
#          uri: lb://backendweb
#          predicates:
#            - Path=/backweb/**
#        - id: consumerModule
#          uri: lb://SECOND-SERVICE
#          predicates:
#            - Path=/consumer/**